name: pair_trading
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pandas
  - pandas-ta
  - pandas-datareader
  - seaborn
  - numpy=1.26.4
  - sqlite
  - python=3.11
  - dash
  - dash-bootstrap-components
  - yfinance