name: pair_trading
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy=1.26.4
  - python=3.11
  - yfinance
  - flask
  - flask-cors
  - flask-restful  
  - werkzeug=2.2.2
  - flask-cors
  - sqlalchemy
  - statsmodels