name: pair_trading
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - pandas-ta
  - seaborn
  - numpy=1.26.4
  - sqlite
  - python=3.11
  - dash
  - dash-bootstrap-components
  - dash-ag-grid
  - yfinance
  - flask
  - werkzeug=2.2.2
  - flask-cors